### ISSUE TITLE
What is the correct P2 repository link for the latest chromium?

### ISSUE THREAD

**Issue by vfateev** [maketechnology/cefswt#123]
Both links mentioned in the README are not reachable now.
https://dl.equoplatform.com/chromium-swt-ce/69.0.0/repository
https://dl.equoplatform.com/chromium-cef-ce/69.0.0/repository
They contained com.equo.swt.chromium package and it worked fine.

The following links are reachable:
http://dl.maketechnology.io/chromium-cef/rls/repository
http://dl.maketechnology.io/chromium-swt/rls/repository
But they contain org.eclipse.swt.chromium package which fails:
java.lang.UnsatisfiedLinkError: Could not find resource chromium_subp-4936r26.exe (in subdirectory: chromium-3071 )
	at org.eclipse.swt.internal.chromium.ResourceExpander.findResource(ResourceExpander.java:119)
	at org.eclipse.swt.chromium.Chromium.loadLib(Chromium.java:1642)
	at org.eclipse.swt.chromium.Chromium.<clinit>(Chromium.java:103)
	at org.eclipse.swt.chromium.Browser.<init>(Browser.java:32)

**Comment by lonelion** [comment]
Hi @vfateev,

I'm sorry to hear that and thank you for reporting it. Last week we had massive hits to the open source p2 repos from some places, and because of that we experienced a lot of problems with the servers. We will take a look at them again and let you know.

For users that want the latest Chromium updates and security fixes, we developed Equo Chromium Enterprise (currently on version 88), which is a cross-platform, modern, performant, and stable SWT browser implementation. It works on Windows, macOS and Linux. Besides all the advantages this SWT browser has, our offering also includes: premium customer support, 100% Guaranteed SLA, specific features, critical security updates, bug fixing, 32-bit compatibility, ready-to-use binaries repositories, updates to newer CEF versions, compatibility with older systems, specific integration scenarios and features, among other benefits.

Please [contact us](mailto:contact@equoplatform.com) for more information.

Thank you!

**Comment by vfateev** [comment]
Could you estimate when the links are available again? And will they be available only for enterprise users?

**Comment by lonelion** [comment]
Hi @vfateev ,

We should have them working by the end of this week. They will be available for everyone. I'll let you know when we have it fixed.
